
import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 * The main class of the Employee Management System Project.
 * @author Longman Xu and Tommy Huang
 */
public class MainJFrame extends javax.swing.JFrame {
	
	// useful global variable declarations
	private static EmployeeHashTable employeeTable;	// the employee hash table
	private static Settings settings;	// the object for managing settings
	private static boolean fileSavedBefore = false;
	
	/**
	 * Creates new form MainJFrame 
	 */
	public MainJFrame() {
		initComponents();
		jComboBox1.setSelectedItem(settings.getLookAndFeel());
		initEmployeeJTable(employeeTable, jTable1);
		jTable1.setAutoCreateRowSorter(true);
		saveFileChooser.setFileFilter(new FileNameExtensionFilter(".em files", "em"));
		openFileChooser.setFileFilter(new FileNameExtensionFilter(".em files", "em"));
	}
	
	/**
	 * The entry point into the program.
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		// open the saved employee hash table
		try {
			employeeTable = EmployeeHashTable.open("saved_employees.em");
		} catch (IOException | ClassNotFoundException e) {
			System.err.println("Error when opening table. Creating new table instead.");
			e.printStackTrace(System.err);
			employeeTable = new EmployeeHashTable(10);
		}
		
		// open the saved settings
		settings = Settings.open("settings.cfg");
		
		/* Set the look and feel from the settings*/
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code">
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (settings.getLookAndFeel().equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			System.err.println("Error encountered while setting the look and feel.");
			ex.printStackTrace(System.err);
		}
		//</editor-fold>
		
		/* Autogenerated code: Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}
	
	private void initEmployeeJTable(EmployeeHashTable hashTable, javax.swing.JTable table) {
		DefaultTableModel employeeTableModel = (DefaultTableModel) table.getModel();
		EmployeeArrayList employeeList = hashTable.returnAllEmployees();
		for (EmployeeInfo employee : employeeList) {
			Object[] rowData = {
				employee.getEmployeeNumber(),
				employee.getFirstName(),
				employee.getLastName(),
				employee.getWorkLocation(),
				employee.getClass()
			};
			employeeTableModel.addRow(rowData);
		}
		table.setModel(employeeTableModel);
	}
	
	private void addToEmployeeJTable(EmployeeInfo newEmployee, javax.swing.JTable table) {
		DefaultTableModel employeeTableModel = (DefaultTableModel) table.getModel();
		Object[] rowData = {
			newEmployee.getEmployeeNumber(),
			newEmployee.getFirstName(),
			newEmployee.getLastName(),
			newEmployee.getWorkLocation(),
			newEmployee.getClass()
		};
		employeeTableModel.addRow(rowData);
		table.setModel(employeeTableModel);
	}
	
	private void updateEmployeeJtable(javax.swing.JTable table, int empNumber) {
		DefaultTableModel employeeTableModel = (DefaultTableModel) table.getModel();
		EmployeeArrayList employeeList = employeeTable.returnAllEmployees();
		int row = -1;
		for (int i = 0; i < employeeList.size(); i++) {
			if (employeeList.get(i).getEmployeeNumber() == empNumber) {
				row = i;
				break;
			}
		}
		employeeTableModel.removeRow(row);
		EmployeeInfo modifiedEmployee = employeeTable.returnAllEmployees().get(row);
		Object[] rowData = {
			modifiedEmployee.getEmployeeNumber(),
			modifiedEmployee.getFirstName(),
			modifiedEmployee.getLastName(),
			modifiedEmployee.getWorkLocation(),
			modifiedEmployee.getClass()
		};
		employeeTableModel.insertRow(row, rowData);
		table.setModel(employeeTableModel);
	}
		
	private void changeSelection(int type) {
		if (type == 0) { // full time
			labelFull0.setVisible(true);
			fieldSalary.setVisible(true);
			
			labelPart0.setVisible(false);
			fieldHourWage.setVisible(false);
			labelPart1.setVisible(false);
			fieldHourWeek.setVisible(false);
			labelPart2.setVisible(false);
			fieldWeekYear.setVisible(false);
		}
		else if (type == 1) { // part time
			labelFull0.setVisible(false);
			fieldSalary.setVisible(false);
			
			labelPart0.setVisible(true);
			fieldHourWage.setVisible(true);
			labelPart1.setVisible(true);
			fieldHourWeek.setVisible(true);
			labelPart2.setVisible(true);
			fieldWeekYear.setVisible(true);
		}
	}
	
	public void getAngryAtUser(String msg) {
		if(msg.isEmpty()) {
			errorMsgLabel.setText("Error");
		}
		else{
			errorMsgLabel.setText(msg);
		}
		errorPopup.setVisible(true);
	}
	
	// clears all the text in the "add" popup menu
	private void clearFields() {
		// clear all text fields
		fieldNumber.setText("");
		fieldFName.setText("");
		fieldLName.setText("");
		fieldDedRate.setText("");
		fieldHourWage.setText("");
		fieldHourWeek.setText("");
		fieldWeekYear.setText("");
		fieldSalary.setText("");
		// reset all drop down menus
		dropDownLocation.setSelectedIndex(0);
		dropDownSexes.setSelectedIndex(0);
		dropDownLocation.setSelectedIndex(0);
		
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPopup = new javax.swing.JDialog();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dropDownType = new javax.swing.JComboBox<>();
        fieldLName = new javax.swing.JTextField();
        fieldFName = new javax.swing.JTextField();
        fieldNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dropDownSexes = new javax.swing.JComboBox<>();
        addTheEmployee = new javax.swing.JButton();
        labelFull0 = new javax.swing.JLabel();
        labelRate = new javax.swing.JLabel();
        fieldSalary = new javax.swing.JTextField();
        fieldDedRate = new javax.swing.JTextField();
        labelPart0 = new javax.swing.JLabel();
        labelPart1 = new javax.swing.JLabel();
        labelPart2 = new javax.swing.JLabel();
        fieldHourWage = new javax.swing.JTextField();
        fieldHourWeek = new javax.swing.JTextField();
        fieldWeekYear = new javax.swing.JTextField();
        dropDownLocation = new javax.swing.JComboBox<>();
        errorPopup = new javax.swing.JDialog();
        errorMsgLabel = new javax.swing.JLabel();
        openDialog = new javax.swing.JDialog();
        openFileChooser = new javax.swing.JFileChooser();
        saveDialog = new javax.swing.JDialog();
        saveFileChooser = new javax.swing.JFileChooser();
        locationDialog = new javax.swing.JDialog();
        locationTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        confirmLocationButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ManagerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        delButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        addLocationsButton = new javax.swing.JButton();
        filePanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        settingsPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        addPopup.setTitle("Add an employee");
        addPopup.setMinimumSize(new java.awt.Dimension(600, 400));
        addPopup.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        addPopup.setResizable(false);

        backButton.setText("cancel");
        backButton.setToolTipText("");
        backButton.setMaximumSize(new java.awt.Dimension(70, 25));
        backButton.setMinimumSize(new java.awt.Dimension(70, 25));
        backButton.setPreferredSize(new java.awt.Dimension(70, 25));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Emp. #");

        jLabel3.setText("First name");

        jLabel4.setText("Last name");

        jLabel5.setText("Location");

        jLabel7.setText("Emp. Type");

        dropDownType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full time", "Part time" }));
        dropDownType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownTypeActionPerformed(evt);
            }
        });

        jLabel8.setText("Sex");

        dropDownSexes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        addTheEmployee.setText("add");
        addTheEmployee.setToolTipText("");
        addTheEmployee.setMaximumSize(new java.awt.Dimension(70, 25));
        addTheEmployee.setMinimumSize(new java.awt.Dimension(70, 25));
        addTheEmployee.setPreferredSize(new java.awt.Dimension(70, 25));
        addTheEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTheEmployeeActionPerformed(evt);
            }
        });

        labelFull0.setText("Salary");

        labelRate.setText("Deductions rate");

        labelPart0.setText("Hourly Wage");

        labelPart1.setText("Hours per week");

        labelPart2.setText("Weeks per year");

        dropDownLocation.setMaximumRowCount(15);

        javax.swing.GroupLayout addPopupLayout = new javax.swing.GroupLayout(addPopup.getContentPane());
        addPopup.getContentPane().setLayout(addPopupLayout);
        addPopupLayout.setHorizontalGroup(
            addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPopupLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldNumber)
                    .addComponent(fieldFName)
                    .addComponent(fieldLName)
                    .addComponent(dropDownSexes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDownType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dropDownLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPopupLayout.createSequentialGroup()
                        .addComponent(labelFull0)
                        .addGap(18, 18, 18)
                        .addComponent(fieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPopupLayout.createSequentialGroup()
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPart0, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPart1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPart2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldWeekYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldHourWage, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(fieldHourWeek))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addPopupLayout.createSequentialGroup()
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addTheEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPopupLayout.createSequentialGroup()
                            .addComponent(labelRate)
                            .addGap(18, 18, 18)
                            .addComponent(fieldDedRate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(111, 111, 111))
        );
        addPopupLayout.setVerticalGroup(
            addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPopupLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFull0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPopupLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dropDownLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPopupLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPart0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldHourWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldHourWeek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldWeekYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPart2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPopupLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTheEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPopupLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dropDownType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(labelRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldDedRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(addPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dropDownSexes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(29, 29, 29))
        );

        errorPopup.setTitle("ERROR");
        errorPopup.setMinimumSize(new java.awt.Dimension(300, 150));
        errorPopup.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        errorPopup.setSize(new java.awt.Dimension(300, 150));

        errorMsgLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        errorMsgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/error.png"))); // NOI18N
        errorMsgLabel.setText("Enter ur error msg here");
        errorMsgLabel.setMaximumSize(new java.awt.Dimension(300, 150));
        errorMsgLabel.setMinimumSize(new java.awt.Dimension(300, 150));
        errorMsgLabel.setName(""); // NOI18N
        errorMsgLabel.setPreferredSize(new java.awt.Dimension(300, 150));

        javax.swing.GroupLayout errorPopupLayout = new javax.swing.GroupLayout(errorPopup.getContentPane());
        errorPopup.getContentPane().setLayout(errorPopupLayout);
        errorPopupLayout.setHorizontalGroup(
            errorPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        errorPopupLayout.setVerticalGroup(
            errorPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPopupLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(errorMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        openDialog.setMinimumSize(new java.awt.Dimension(710, 450));
        openDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        openDialog.setResizable(false);

        openFileChooser.setMinimumSize(new java.awt.Dimension(710, 410));
        openFileChooser.setPreferredSize(new java.awt.Dimension(710, 410));
        openFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout openDialogLayout = new javax.swing.GroupLayout(openDialog.getContentPane());
        openDialog.getContentPane().setLayout(openDialogLayout);
        openDialogLayout.setHorizontalGroup(
            openDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openDialogLayout.createSequentialGroup()
                .addComponent(openFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );
        openDialogLayout.setVerticalGroup(
            openDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(openFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        saveDialog.setMinimumSize(new java.awt.Dimension(710, 450));
        saveDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        saveDialog.setResizable(false);

        saveFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        saveFileChooser.setMinimumSize(new java.awt.Dimension(710, 410));
        saveFileChooser.setPreferredSize(new java.awt.Dimension(710, 410));
        saveFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveDialogLayout = new javax.swing.GroupLayout(saveDialog.getContentPane());
        saveDialog.getContentPane().setLayout(saveDialogLayout);
        saveDialogLayout.setHorizontalGroup(
            saveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saveFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        saveDialogLayout.setVerticalGroup(
            saveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saveFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        locationDialog.setTitle("Add a location");
        locationDialog.setMinimumSize(new java.awt.Dimension(400, 200));
        locationDialog.setModal(true);
        locationDialog.setResizable(false);

        jLabel10.setText("New location:");

        confirmLocationButton.setText("Confirm");
        confirmLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmLocationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout locationDialogLayout = new javax.swing.GroupLayout(locationDialog.getContentPane());
        locationDialog.getContentPane().setLayout(locationDialogLayout);
        locationDialogLayout.setHorizontalGroup(
            locationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationDialogLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(locationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmLocationButton)
                    .addGroup(locationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        locationDialogLayout.setVerticalGroup(
            locationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationDialogLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(locationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(confirmLocationButton)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management System");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        ManagerPanel.setPreferredSize(new java.awt.Dimension(700, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp #", "First", "Last", "Location", "Emp. Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "attributes", "information"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable2PropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        delButton.setBackground(new java.awt.Color(255, 102, 102));
        delButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/trash.png"))); // NOI18N
        delButton.setText("remove");
        delButton.setActionCommand("delButton");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(102, 255, 102));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/add.png"))); // NOI18N
        addButton.setText("add");
        addButton.setActionCommand("addButton");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("double click on a value to edit it");

        addLocationsButton.setBackground(new java.awt.Color(102, 102, 255));
        addLocationsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/marker.png"))); // NOI18N
        addLocationsButton.setText("<html>Add<br />locations</html>");
        addLocationsButton.setActionCommand("addButton");
        addLocationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerPanelLayout = new javax.swing.GroupLayout(ManagerPanel);
        ManagerPanel.setLayout(ManagerPanelLayout);
        ManagerPanelLayout.setHorizontalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addLocationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );
        ManagerPanelLayout.setVerticalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addButton)
                        .addComponent(delButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLocationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jTabbedPane1.addTab("<html>Manage<br />& Add</html>", new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/employee.png")), ManagerPanel, "cats"); // NOI18N

        filePanel.setPreferredSize(new java.awt.Dimension(700, 600));

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/newfolder.png"))); // NOI18N
        newButton.setText("buttonNew");
        newButton.setMaximumSize(new java.awt.Dimension(187, 92));
        newButton.setMinimumSize(new java.awt.Dimension(187, 92));
        newButton.setName(""); // NOI18N

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/open.png"))); // NOI18N
        openButton.setText("buttonOpen");
        openButton.setMaximumSize(new java.awt.Dimension(187, 92));
        openButton.setMinimumSize(new java.awt.Dimension(187, 92));
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/save.png"))); // NOI18N
        saveButton.setText("buttonSave");
        saveButton.setMaximumSize(new java.awt.Dimension(187, 92));
        saveButton.setMinimumSize(new java.awt.Dimension(187, 92));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        saveAsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/saveAs.png"))); // NOI18N
        saveAsButton.setText("buttonSaveAs");
        saveAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePanelLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveAsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveAsButton)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("File", new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/file.png")), filePanel); // NOI18N

        settingsPanel.setPreferredSize(new java.awt.Dimension(700, 600));

        jComboBox1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Windows", "Windows Classic", "Nimbus", "Metal", "Dark Metal", "Dark Nimbus" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Look and Feel (requires restart):");

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(433, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/settings.png")), settingsPanel); // NOI18N

        helpPanel.setPreferredSize(new java.awt.Dimension(700, 600));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/clippy.jpg"))); // NOI18N
        jButton5.setToolTipText("Clippy will solve all your problems!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Made by Longman Xu and Tommy Huang");

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton5)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(25, 25, 25))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpPanelLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("<html>Help &<br />About</html>", new javax.swing.ImageIcon(getClass().getResource("/iconsPackage/help.png")), helpPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		// change the default theme on next startup
		settings.setLookAndFeel((String) jComboBox1.getSelectedItem());
		try{
			settings.save();
		} catch (IOException e){
			getAngryAtUser("Error while saving settings.");
			e.printStackTrace(System.err);
		}
    }//GEN-LAST:event_jComboBox1ActionPerformed
	
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		// save the employees 
		try {
			employeeTable.save("saved_employees.em");
			System.out.println("Saved all employees");
		} catch (IOException e) {
			System.err.println("Error encountered when saving employees:");
			e.printStackTrace(System.err);
		}
    }//GEN-LAST:event_formWindowClosing
	
    private void addTheEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTheEmployeeActionPerformed
        // check to make sure none of the text fields are empty
        // Update this if everytime we add/del a field
        if (fieldNumber.getText().isEmpty() || fieldFName.getText().isEmpty() || fieldLName.getText().isEmpty()){
			getAngryAtUser("Some of the fields are empty!!! :(");
        }
        else if(dropDownType.getSelectedItem().equals("Full time") && fieldNumber.getText().isEmpty() == false) {
            // do full time stuff
			try {
				FullTimeEmployee temp = new FullTimeEmployee(Integer.parseInt(fieldNumber.getText()), fieldFName.getText(), fieldLName.getText(),
						dropDownSexes.getSelectedIndex(), dropDownLocation.getSelectedIndex(), Double.parseDouble(fieldDedRate.getText()), Double.parseDouble(fieldSalary.getText()));
				employeeTable.add(temp);
				addToEmployeeJTable(temp, jTable1);
				addPopup.setVisible(false);
				clearFields();
			}
			catch (IllegalArgumentException e) {
				getAngryAtUser(e.getMessage());
			}
        }
        else if (dropDownType.getSelectedItem().equals("Part time") && fieldHourWage.getText().isEmpty() == false && fieldHourWeek.getText().isEmpty() == false && fieldWeekYear.getText().isEmpty() == false) {
            // do part time stuff
			try {
				PartTimeEmployee temp = new PartTimeEmployee(Integer.parseInt(fieldNumber.getText()), fieldFName.getText(), fieldLName.getText(),
					dropDownSexes.getSelectedIndex(), dropDownLocation.getSelectedIndex(), Double.parseDouble(fieldDedRate.getText()), Double.parseDouble(fieldHourWage.getText()), Double.parseDouble(fieldHourWeek.getText()), Double.parseDouble(fieldWeekYear.getText()));
				employeeTable.add(temp);
				addToEmployeeJTable(temp, jTable1);
				addPopup.setVisible(false);
				clearFields();
			}
			catch (IllegalArgumentException e) {
				getAngryAtUser(e.getMessage());
			}
        }
    }//GEN-LAST:event_addTheEmployeeActionPerformed
	
    private void dropDownTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownTypeActionPerformed
        if (dropDownType.getSelectedItem().equals("Full time")) {
			changeSelection(0);
        }
		else if (dropDownType.getSelectedItem().equals("Part time")) {
			changeSelection(1);
		}
    }//GEN-LAST:event_dropDownTypeActionPerformed
	
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setFocusableWindowState(true);
        addPopup.setVisible(false);

    }//GEN-LAST:event_backButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
		JFileChooser chooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
		chooser.setFileFilter(filter);
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			System.out.println("You chose to open this file: " + chooser.getSelectedFile().getName());
		}
    }//GEN-LAST:event_openButtonActionPerformed

    private void openFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openFileChooserActionPerformed

    private void saveAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsButtonActionPerformed
		JFileChooser chooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
		chooser.setFileFilter(filter);
		int returnVal = chooser.showSaveDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			System.out.println("You chose to save this file as: " + chooser.getSelectedFile().getName());
		}
    }//GEN-LAST:event_saveAsButtonActionPerformed

    private void saveFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveFileChooserActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
		
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // this.setVisible(false);
		int numItems = dropDownLocation.getItemCount();
		if (numItems == 0) {
			getAngryAtUser("No locations have been added yet!");
			return;
		}
		
        if (dropDownType.getSelectedItem().equals("Full time")) {
            changeSelection(0);
        }
        else if (dropDownType.getSelectedItem().equals("Part time")) {
            changeSelection(1);
        }

        addPopup.setVisible(true);

    }//GEN-LAST:event_addButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            getAngryAtUser("no selected employee to remove!");
        }
        else {
            int selRow = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());
            DefaultTableModel employeeTableModel = (DefaultTableModel) jTable1.getModel();
            employeeTable.remove((int) employeeTableModel.getValueAt(selRow, 0));
            employeeTableModel.removeRow(selRow);
            jTable1.setModel(employeeTableModel);
            DefaultTableModel attributeTableModel = (DefaultTableModel) jTable2.getModel();
            attributeTableModel.setColumnCount(0);
        }

        // TODO: update table
    }//GEN-LAST:event_delButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getRowSelectionAllowed()) {
            int selRow = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());
            DefaultTableModel employeeTableModel = (DefaultTableModel) jTable1.getModel();
            int selectedEmpNumber = (int) employeeTableModel.getValueAt(selRow, 0);
            EmployeeInfo selectedEmployee = employeeTable.find(selectedEmpNumber);
            // System.out.println(selectedEmployee.getFirstName());

            DefaultTableModel attributeTableModel = (DefaultTableModel) jTable2.getModel();
            EmployeeArrayList employeeList = employeeTable.returnAllEmployees();

            attributeTableModel.setColumnCount(0);
            attributeTableModel.setRowCount(6);
            // run through every employee in employeeList
            // add the part time employee info as a column
            if (selectedEmployee instanceof PartTimeEmployee) {
                Object[] info = {
                    selectedEmployee.getEmployeeNumber(),
                    selectedEmployee.getFirstName(),
                    selectedEmployee.getLastName(),
					selectedEmployee.getSex(),
                    selectedEmployee.getWorkLocation(),
                    selectedEmployee.getClass(),
                    selectedEmployee.getDeductionsRate(),
                    ((PartTimeEmployee) selectedEmployee).getHourlyWage(),
                    ((PartTimeEmployee) selectedEmployee).getHoursPerWeek(),
                    ((PartTimeEmployee) selectedEmployee).getWeeksPerYear(),
                    selectedEmployee.calcAnnualNetIncome()
                };
                Object[] firstColInfo = {
                    "employee number",
                    "first name",
                    "last name",
                    "sex",
                    "work location",
					"type",
                    "deducations rate",
                    "hourly wage",
                    "hours per week",
                    "weeks per year",
                    "net income"
                };
                attributeTableModel.addColumn("attributes", firstColInfo);
                attributeTableModel.addColumn("information", info);
            }
            else if (selectedEmployee instanceof FullTimeEmployee) {
                Object[] info = {
                    selectedEmployee.getEmployeeNumber(),
                    selectedEmployee.getFirstName(),
                    selectedEmployee.getLastName(),
					selectedEmployee.getSex(),
                    selectedEmployee.getWorkLocation(),
                    selectedEmployee.getClass(),
                    selectedEmployee.getDeductionsRate(),
                    ((FullTimeEmployee) selectedEmployee).getYearlySalary(),
                    selectedEmployee.calcAnnualNetIncome()

                };
                Object[] firstColInfo = {
                    "employee number",
                    "first name",
                    "last name",
                    "sex",
                    "work location",
					"type",
                    "deducations rate",
                    "salary",
                    "net income"
                };
                attributeTableModel.addColumn("attributes", firstColInfo);
                attributeTableModel.addColumn("information", info);
            }

            // int colIndex = jTable1.getSelectedColumn();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void addLocationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocationsButtonActionPerformed
        // TODO add your handling code here:
		locationDialog.setVisible(true);
    }//GEN-LAST:event_addLocationsButtonActionPerformed

    private void jTable2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable2PropertyChange
		if (evt.getNewValue() == null) {
			DefaultTableModel a = (DefaultTableModel) jTable2.getModel();
			Object hwat = a.getValueAt(0, 1);
			int employeeNumber = (int) a.getValueAt(0, 1);
			int parameterRow = jTable2.getSelectedRow();
			String newValue = (String) a.getValueAt(parameterRow, 1);
			EmployeeInfo targetEmployee = employeeTable.find(employeeNumber);
			boolean validChange = false;
			System.out.println(parameterRow);
			switch (parameterRow) {
				case 1:
					targetEmployee.setFirstName((String) newValue);
					validChange = true;
					break;
				case 2:
					targetEmployee.setLastName((String) newValue);
					validChange = true;
					break;
				case 3:
					targetEmployee.setSex(Integer.parseInt(newValue));
					validChange = true;
					break;
				case 6:
					targetEmployee.setDeductionsRate(Double.parseDouble(newValue));
					validChange = true;
					break;
				case 7:
					if (targetEmployee instanceof FullTimeEmployee) {
						((FullTimeEmployee) targetEmployee).setYearlySalary(Double.parseDouble(newValue));
						validChange = true;
						break;
					}
					else if (targetEmployee instanceof PartTimeEmployee) {
						((PartTimeEmployee) targetEmployee).setHourlyWage(Double.parseDouble(newValue));
						validChange = true;
						break;
					}
				case 8:
					if (targetEmployee instanceof PartTimeEmployee) {
						((PartTimeEmployee) targetEmployee).setHoursPerWeek(Double.parseDouble(newValue));
						validChange = true;
						break;
					}
				case 9:
					if (targetEmployee instanceof PartTimeEmployee) {
						((PartTimeEmployee) targetEmployee).setWeeksPerYear(Double.parseDouble(newValue));
						validChange = true;
						break;
					}
				default:
					getAngryAtUser("Cannot modify this parameter!");
					break;
			}
			if (validChange) {
				updateEmployeeJtable(jTable1, employeeNumber);
			}
		}
    }//GEN-LAST:event_jTable2PropertyChange

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void confirmLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmLocationButtonActionPerformed
        // TODO add your handling code here:
		// add the location
		employeeTable.addLocation(locationTextField.getText());
		dropDownLocation.addItem(locationTextField.getText());
		// hide the dialog and clear text
		locationTextField.setText("");
		locationDialog.setVisible(false);
		
    }//GEN-LAST:event_confirmLocationButtonActionPerformed
	
	// <editor-fold defaultstate="collapsed" desc="Auto-generated Variables Declarations">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ManagerPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addLocationsButton;
    private javax.swing.JDialog addPopup;
    private javax.swing.JButton addTheEmployee;
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmLocationButton;
    private javax.swing.JButton delButton;
    private javax.swing.JComboBox<String> dropDownLocation;
    private javax.swing.JComboBox<String> dropDownSexes;
    private javax.swing.JComboBox<String> dropDownType;
    private javax.swing.JLabel errorMsgLabel;
    private javax.swing.JDialog errorPopup;
    private javax.swing.JTextField fieldDedRate;
    private javax.swing.JTextField fieldFName;
    private javax.swing.JTextField fieldHourWage;
    private javax.swing.JTextField fieldHourWeek;
    private javax.swing.JTextField fieldLName;
    private javax.swing.JTextField fieldNumber;
    private javax.swing.JTextField fieldSalary;
    private javax.swing.JTextField fieldWeekYear;
    private javax.swing.JPanel filePanel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelFull0;
    private javax.swing.JLabel labelPart0;
    private javax.swing.JLabel labelPart1;
    private javax.swing.JLabel labelPart2;
    private javax.swing.JLabel labelRate;
    private javax.swing.JDialog locationDialog;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JDialog openDialog;
    private javax.swing.JFileChooser openFileChooser;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JDialog saveDialog;
    private javax.swing.JFileChooser saveFileChooser;
    private javax.swing.JPanel settingsPanel;
    // End of variables declaration//GEN-END:variables
	// </editor-fold>
}